# Use root/example as user/password credentials
version: '3.6'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd
    volumes:
    #   - ./dbscript/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - db:/data/db/

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: P@ssw0rd
  #   depends_on:
  #     - mongo
