version: "3.6"

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: demo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd
    volumes:
      - ../mongodb/db:C:/data/db
    ports:
      - 27017:27017
    expose:
    # Opens port 27017 on the container
    - '27017'
    # Where our data will be persisted